window.raceData = {
  "races": [
    {
      "raceId": 1,
      "trackName": "Abu Dhabi",
      "weather": "Dry",
      "results": [
        {"position": 1, "name": "Lando Norris", "team": "McLaren", "points": 25, "time": 5193.29, "overtakes": 0, "tyreDegradation": 75, "pits": 1},
        {"position": 2, "name": "Carlos Sainz", "team": "Ferrari", "points": 18, "time": 5199.12, "overtakes": 0, "tyreDegradation": 75, "pits": 1},
        {"position": 3, "name": "Charles Leclerc", "team": "Ferrari", "points": 15, "time": 5225.22, "overtakes": 9, "tyreDegradation": 76, "pits": 1},
        {"position": 4, "name": "Lewis Hamilton", "team": "Mercedes", "points": 12, "time": 5229.77, "overtakes": 10, "tyreDegradation": 73, "pits": 1},
        {"position": 5, "name": "George Russell", "team": "Mercedes", "points": 10, "time": 5230.83, "overtakes": 3, "tyreDegradation": 75, "pits": 1},
        {"position": 6, "name": "Max Verstappen", "team": "Red Bull", "points": 8, "time": 5243.14, "overtakes": 13, "tyreDegradation": 74, "pits": 1},
        {"position": 7, "name": "Pierre Gasly", "team": "Alpine", "points": 6, "time": 5265.85, "overtakes": 5, "tyreDegradation": 76, "pits": 1},
        {"position": 8, "name": "Nico Hulkenberg", "team": "Haas", "points": 4, "time": 5268.85, "overtakes": 5, "tyreDegradation": 76, "pits": 1},
        {"position": 9, "name": "Fernando Alonso", "team": "Aston Martin", "points": 2, "time": 5275.66, "overtakes": 7, "tyreDegradation": 73, "pits": 2},
        {"position": 10, "name": "Oscar Piastri", "team": "McLaren", "points": 1, "time": 5277.11, "overtakes": 13, "tyreDegradation": 74, "pits": 2},
        {"position": 11, "name": "Esteban Ocon", "team": "Alpine", "points": 0, "time": 11600, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 12, "name": "Sergio Perez", "team": "Red Bull", "points": 0, "time": 11600, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 13, "name": "Alex Albon", "team": "Williams", "points": 0, "time": 5404.54, "overtakes": 7, "tyreDegradation": 75, "pits": 1},
        {"position": 14, "name": "Franco Colapinto", "team": "Williams", "points": 0, "time": 8870.43, "overtakes": 0, "tyreDegradation": 32, "pits": 1},
        {"position": 15, "name": "Lance Stroll", "team": "Aston Martin", "points": 0, "time": 5406.76, "overtakes": 6, "tyreDegradation": 71, "pits": 2},
        {"position": 16, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 0, "time": 8447.28, "overtakes": 1, "tyreDegradation": 35, "pits": 1},
        {"position": 17, "name": "Jack Doohan", "team": "Alpine", "points": 0, "time": 5419.85, "overtakes": 7, "tyreDegradation": 73, "pits": 1},
        {"position": 18, "name": "Liam Lawson", "team": "RB", "points": 0, "time": 5676.95, "overtakes": 6, "tyreDegradation": 67, "pits": 3},
        {"position": 19, "name": "Kevin Magnussen", "team": "Haas", "points": 0, "time": 5470.89, "overtakes": 2, "tyreDegradation": 32, "pits": 4},
        {"position": 20, "name": "Oliver Bearman", "team": "Haas", "points": 0, "time": 11600, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 21, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 0, "time": 5410.59, "overtakes": 8, "tyreDegradation": 68, "pits": 2},
        {"position": 22, "name": "Yuki Tsunoda", "team": "RB", "points": 0, "time": 5408.03, "overtakes": 11, "tyreDegradation": 73, "pits": 1}
      ]
    },
    {
      "raceId": 2,
      "trackName": "Brazil",
      "weather": "Rainy",
      "results": [
        {"position": 1, "name": "Max Verstappen", "team": "Red Bull", "points": 25, "time": 5169.28, "overtakes": 10, "tyreDegradation": 80, "pits": 1},
        {"position": 2, "name": "Esteban Ocon", "team": "Alpine", "points": 18, "time": 5179.67, "overtakes": 3, "tyreDegradation": 80, "pits": 1},
        {"position": 3, "name": "Pierre Gasly", "team": "Alpine", "points": 15, "time": 5188.24, "overtakes": 6, "tyreDegradation": 80, "pits": 1},
        {"position": 4, "name": "George Russell", "team": "Mercedes", "points": 12, "time": 5192.64, "overtakes": 4, "tyreDegradation": 80, "pits": 2},
        {"position": 5, "name": "Lando Norris", "team": "McLaren", "points": 10, "time": 5199.65, "overtakes": 4, "tyreDegradation": 80, "pits": 2},
        {"position": 6, "name": "Charles Leclerc", "team": "Ferrari", "points": 8, "time": 5202.1, "overtakes": 7, "tyreDegradation": 80, "pits": 2},
        {"position": 7, "name": "Oscar Piastri", "team": "McLaren", "points": 6, "time": 5209.39, "overtakes": 5, "tyreDegradation": 80, "pits": 2},
        {"position": 8, "name": "Yuki Tsunoda", "team": "RB", "points": 4, "time": 5211.16, "overtakes": 5, "tyreDegradation": 80, "pits": 2},
        {"position": 9, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 2, "time": 5216.12, "overtakes": 4, "tyreDegradation": 80, "pits": 4},
        {"position": 10, "name": "Liam Lawson", "team": "RB", "points": 1, "time": 5229.49, "overtakes": 4, "tyreDegradation": 80, "pits": 2},
        {"position": 11, "name": "Lewis Hamilton", "team": "Mercedes", "points": 0, "time": 5229.67, "overtakes": 5, "tyreDegradation": 80, "pits": 2},
        {"position": 12, "name": "Oliver Bearman", "team": "Haas", "points": 0, "time": 5242.07, "overtakes": 13, "tyreDegradation": 80, "pits": 2},
        {"position": 13, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "time": 5242.55, "overtakes": 6, "tyreDegradation": 80, "pits": 2},
        {"position": 14, "name": "Sergio Perez", "team": "Red Bull", "points": 0, "time": 5246.5, "overtakes": 7, "tyreDegradation": 80, "pits": 2},
        {"position": 15, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 0, "time": 5251.13, "overtakes": 7, "tyreDegradation": 80, "pits": 1},
        {"position": 16, "name": "Franco Colapinto", "team": "Williams", "points": 0, "time": 8708.26, "overtakes": 2, "tyreDegradation": 9, "pits": 1},
        {"position": 17, "name": "Nico Hulkenberg", "team": "Haas", "points": 0, "time": 8384.31, "overtakes": 4, "tyreDegradation": 0, "pits": 3},
        {"position": 18, "name": "Lance Stroll", "team": "Aston Martin", "points": 0, "time": 12000, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 19, "name": "Alex Albon", "team": "Williams", "points": 0, "time": 12000, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 20, "name": "Kevin Magnussen", "team": "Haas", "points": 0, "time": 12000, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 21, "name": "Jack Doohan", "team": "Alpine", "points": 0, "time": 12000, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 22, "name": "Carlos Sainz", "team": "Ferrari", "points": 0, "time": 7665.72, "overtakes": 8, "tyreDegradation": 17, "pits": 2}
      ]
    },
    {
      "raceId": 3,
      "trackName": "Las Vegas",
      "weather": "Dry",
      "results": [
        {"position": 1, "name": "George Russell", "team": "Mercedes", "points": 25, "time": 4925.97, "overtakes": 1, "tyreDegradation": 51, "pits": 2},
        {"position": 2, "name": "Lewis Hamilton", "team": "Mercedes", "points": 18, "time": 4933.28, "overtakes": 13, "tyreDegradation": 55, "pits": 2},
        {"position": 3, "name": "Carlos Sainz", "team": "Ferrari", "points": 15, "time": 4937.88, "overtakes": 9, "tyreDegradation": 55, "pits": 2},
        {"position": 4, "name": "Charles Leclerc", "team": "Ferrari", "points": 12, "time": 4940.25, "overtakes": 8, "tyreDegradation": 52, "pits": 2},
        {"position": 5, "name": "Max Verstappen", "team": "Red Bull", "points": 10, "time": 4942.55, "overtakes": 8, "tyreDegradation": 55, "pits": 2},
        {"position": 6, "name": "Lando Norris", "team": "McLaren", "points": 8, "time": 4969.35, "overtakes": 10, "tyreDegradation": 13, "pits": 3},
        {"position": 7, "name": "Oscar Piastri", "team": "McLaren", "points": 6, "time": 4977.33, "overtakes": 14, "tyreDegradation": 57, "pits": 2},
        {"position": 8, "name": "Nico Hulkenberg", "team": "Haas", "points": 4, "time": 4985.78, "overtakes": 14, "tyreDegradation": 50, "pits": 2},
        {"position": 9, "name": "Yuki Tsunoda", "team": "RB", "points": 2, "time": 4988.78, "overtakes": 8, "tyreDegradation": 54, "pits": 2},
        {"position": 10, "name": "Sergio Perez", "team": "Red Bull", "points": 1, "time": 4989.08, "overtakes": 17, "tyreDegradation": 51, "pits": 2},
        {"position": 11, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "time": 4995.16, "overtakes": 14, "tyreDegradation": 57, "pits": 2},
        {"position": 12, "name": "Kevin Magnussen", "team": "Haas", "points": 0, "time": 4995.77, "overtakes": 12, "tyreDegradation": 61, "pits": 1},
        {"position": 13, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 0, "time": 5000.05, "overtakes": 12, "tyreDegradation": 49, "pits": 2},
        {"position": 14, "name": "Franco Colapinto", "team": "Williams", "points": 0, "time": 5001.14, "overtakes": 13, "tyreDegradation": 56, "pits": 2},
        {"position": 15, "name": "Lance Stroll", "team": "Aston Martin", "points": 0, "time": 5010.07, "overtakes": 9, "tyreDegradation": 55, "pits": 2},
        {"position": 16, "name": "Liam Lawson", "team": "RB", "points": 0, "time": 5016.97, "overtakes": 10, "tyreDegradation": 43, "pits": 2},
        {"position": 17, "name": "Esteban Ocon", "team": "Alpine", "points": 0, "time": 5128.03, "overtakes": 11, "tyreDegradation": 21, "pits": 3},
        {"position": 18, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 0, "time": 5137.25, "overtakes": 8, "tyreDegradation": 44, "pits": 2},
        {"position": 19, "name": "Pierre Gasly", "team": "Alpine", "points": 0, "time": 8536.97, "overtakes": 2, "tyreDegradation": 8, "pits": 1},
        {"position": 20, "name": "Jack Doohan", "team": "Alpine", "points": 0, "time": 10000, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 21, "name": "Oliver Bearman", "team": "Haas", "points": 0, "time": 10000, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 22, "name": "Alex Albon", "team": "Williams", "points": 0, "time": 7532.02, "overtakes": 7, "tyreDegradation": 25, "pits": 1}
      ]
    },
    {
      "raceId": 4,
      "trackName": "Mexico",
      "weather": "Dry",
      "results": [
        {"position": 1, "name": "Carlos Sainz", "team": "Ferrari", "points": 25, "time": 5171.13, "overtakes": 1, "tyreDegradation": 80, "pits": 1},
        {"position": 2, "name": "Charles Leclerc", "team": "Ferrari", "points": 18, "time": 5178.78, "overtakes": 1, "tyreDegradation": 61, "pits": 1},
        {"position": 3, "name": "Lando Norris", "team": "McLaren", "points": 15, "time": 5179.83, "overtakes": 2, "tyreDegradation": 80, "pits": 1},
        {"position": 4, "name": "George Russell", "team": "Mercedes", "points": 12, "time": 5209.97, "overtakes": 4, "tyreDegradation": 80, "pits": 1},
        {"position": 5, "name": "Lewis Hamilton", "team": "Mercedes", "points": 10, "time": 5210.89, "overtakes": 5, "tyreDegradation": 80, "pits": 1},
        {"position": 6, "name": "Max Verstappen", "team": "Red Bull", "points": 8, "time": 5221.25, "overtakes": 7, "tyreDegradation": 80, "pits": 1},
        {"position": 7, "name": "Kevin Magnussen", "team": "Haas", "points": 6, "time": 5228.23, "overtakes": 6, "tyreDegradation": 80, "pits": 1},
        {"position": 8, "name": "Oscar Piastri", "team": "McLaren", "points": 4, "time": 5234.4, "overtakes": 18, "tyreDegradation": 80, "pits": 1},
        {"position": 9, "name": "Nico Hulkenberg", "team": "Haas", "points": 2, "time": 5240.6, "overtakes": 7, "tyreDegradation": 80, "pits": 1},
        {"position": 10, "name": "Pierre Gasly", "team": "Alpine", "points": 1, "time": 5254.73, "overtakes": 6, "tyreDegradation": 80, "pits": 1},
        {"position": 11, "name": "Lance Stroll", "team": "Aston Martin", "points": 0, "time": 5264.25, "overtakes": 5, "tyreDegradation": 80, "pits": 1},
        {"position": 12, "name": "Liam Lawson", "team": "RB", "points": 0, "time": 5265.52, "overtakes": 10, "tyreDegradation": 64, "pits": 1},
        {"position": 13, "name": "Franco Colapinto", "team": "Williams", "points": 0, "time": 5266.91, "overtakes": 9, "tyreDegradation": 80, "pits": 1},
        {"position": 14, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 0, "time": 5279.02, "overtakes": 9, "tyreDegradation": 80, "pits": 1},
        {"position": 15, "name": "Esteban Ocon", "team": "Alpine", "points": 0, "time": 5282.16, "overtakes": 7, "tyreDegradation": 80, "pits": 1},
        {"position": 16, "name": "Sergio Perez", "team": "Red Bull", "points": 0, "time": 5286.13, "overtakes": 4, "tyreDegradation": 54, "pits": 2},
        {"position": 17, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 0, "time": 5294.99, "overtakes": 5, "tyreDegradation": 80, "pits": 1},
        {"position": 18, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "time": 10526.2, "overtakes": 0, "tyreDegradation": 20, "pits": 0},
        {"position": 19, "name": "Alex Albon", "team": "Williams", "points": 0, "time": 12000, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 20, "name": "Jack Doohan", "team": "Alpine", "points": 0, "time": 12000, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 21, "name": "Yuki Tsunoda", "team": "RB", "points": 0, "time": 12000, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 22, "name": "Oliver Bearman", "team": "Haas", "points": 0, "time": 12000, "overtakes": 0, "tyreDegradation": 0, "pits": 0}
      ]
    },
    {
      "raceId": 5,
      "trackName": "Qatar",
      "weather": "Dry",
      "results": [
        {"position": 1, "name": "Max Verstappen", "team": "Red Bull", "points": 25, "time": 5023.35, "overtakes": 0, "tyreDegradation": 69, "pits": 3},
        {"position": 2, "name": "Lando Norris", "team": "McLaren", "points": 18, "time": 5212.33, "overtakes": 0, "tyreDegradation": 64, "pits": 4},
        {"position": 3, "name": "Charles Leclerc", "team": "Ferrari", "points": 15, "time": 5146.67, "overtakes": 4, "tyreDegradation": 69, "pits": 3},
        {"position": 4, "name": "Lewis Hamilton", "team": "Mercedes", "points": 12, "time": 5173.71, "overtakes": 2, "tyreDegradation": 61, "pits": 4},
        {"position": 5, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 10, "time": 5194.38, "overtakes": 2, "tyreDegradation": 70, "pits": 3},
        {"position": 6, "name": "Oscar Piastri", "team": "McLaren", "points": 8, "time": 5306.6, "overtakes": 3, "tyreDegradation": 69, "pits": 3},
        {"position": 7, "name": "Liam Lawson", "team": "RB", "points": 6, "time": 5368.54, "overtakes": 6, "tyreDegradation": 68, "pits": 4},
        {"position": 8, "name": "George Russell", "team": "Mercedes", "points": 4, "time": 5474.43, "overtakes": 6, "tyreDegradation": 69, "pits": 4},
        {"position": 9, "name": "Pierre Gasly", "team": "Alpine", "points": 2, "time": 5482.1, "overtakes": 8, "tyreDegradation": 69, "pits": 3},
        {"position": 10, "name": "Carlos Sainz", "team": "Ferrari", "points": 1, "time": 5482.8, "overtakes": 3, "tyreDegradation": 69, "pits": 3},
        {"position": 11, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "time": 5485.19, "overtakes": 7, "tyreDegradation": 69, "pits": 3},
        {"position": 12, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 0, "time": 5490.68, "overtakes": 6, "tyreDegradation": 69, "pits": 3},
        {"position": 13, "name": "Kevin Magnussen", "team": "Haas", "points": 0, "time": 5497.5, "overtakes": 8, "tyreDegradation": 69, "pits": 3},
        {"position": 14, "name": "Yuki Tsunoda", "team": "RB", "points": 0, "time": 5526.42, "overtakes": 6, "tyreDegradation": 68, "pits": 4},
        {"position": 15, "name": "Nico Hulkenberg", "team": "Haas", "points": 0, "time": 7434.51, "overtakes": 5, "tyreDegradation": 6, "pits": 4},
        {"position": 16, "name": "Esteban Ocon", "team": "Alpine", "points": 0, "time": 11400, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 17, "name": "Oliver Bearman", "team": "Haas", "points": 0, "time": 11400, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 18, "name": "Jack Doohan", "team": "Alpine", "points": 0, "time": 11400, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 19, "name": "Alex Albon", "team": "Williams", "points": 0, "time": 5678.29, "overtakes": 7, "tyreDegradation": 16, "pits": 4},
        {"position": 20, "name": "Franco Colapinto", "team": "Williams", "points": 0, "time": 11400, "overtakes": 0, "tyreDegradation": 0, "pits": 0},
        {"position": 21, "name": "Lance Stroll", "team": "Aston Martin", "points": 0, "time": 10771.6, "overtakes": 1, "tyreDegradation": 1, "pits": 2},
        {"position": 22, "name": "Sergio Perez", "team": "Red Bull", "points": 0, "time": 7331.89, "overtakes": 5, "tyreDegradation": 3, "pits": 3}
      ]
    }
  ],
  "standings": [
    {"rank": 1, "name": "Max Verstappen", "team": "Red Bull", "points": 76, "totalTime": 25599.6},
    {"rank": 2, "name": "Lando Norris", "team": "McLaren", "points": 76, "totalTime": 25754.5},
    {"rank": 3, "name": "Charles Leclerc", "team": "Ferrari", "points": 68, "totalTime": 25693},
    {"rank": 4, "name": "George Russell", "team": "Mercedes", "points": 63, "totalTime": 26033.8},
    {"rank": 5, "name": "Carlos Sainz", "team": "Ferrari", "points": 59, "totalTime": 28456.6},
    {"rank": 6, "name": "Lewis Hamilton", "team": "Mercedes", "points": 52, "totalTime": 25777.3},
    {"rank": 7, "name": "Oscar Piastri", "team": "McLaren", "points": 25, "totalTime": 26004.8},
    {"rank": 8, "name": "Pierre Gasly", "team": "Alpine", "points": 24, "totalTime": 29727.9},
    {"rank": 9, "name": "Esteban Ocon", "team": "Alpine", "points": 18, "totalTime": 38589.9},
    {"rank": 10, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 10, "totalTime": 29309.1},
    {"rank": 11, "name": "Nico Hulkenberg", "team": "Haas", "points": 10, "totalTime": 31314},
    {"rank": 12, "name": "Liam Lawson", "team": "RB", "points": 7, "totalTime": 26557.5},
    {"rank": 13, "name": "Yuki Tsunoda", "team": "RB", "points": 6, "totalTime": 33134.4},
    {"rank": 14, "name": "Kevin Magnussen", "team": "Haas", "points": 6, "totalTime": 33192.4},
    {"rank": 15, "name": "Fernando Alonso", "team": "Aston Martin", "points": 2, "totalTime": 31524.8},
    {"rank": 16, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 2, "totalTime": 26412.4},
    {"rank": 17, "name": "Sergio Perez", "team": "Red Bull", "points": 1, "totalTime": 34453.6},
    {"rank": 18, "name": "Franco Colapinto", "team": "Williams", "points": 0, "totalTime": 39246.7},
    {"rank": 19, "name": "Lance Stroll", "team": "Aston Martin", "points": 0, "totalTime": 38452.6},
    {"rank": 20, "name": "Oliver Bearman", "team": "Haas", "points": 0, "totalTime": 50242.1},
    {"rank": 21, "name": "Alex Albon", "team": "Williams", "points": 0, "totalTime": 42614.9},
    {"rank": 22, "name": "Jack Doohan", "team": "Alpine", "points": 0, "totalTime": 50819.8}
  ]
};
