window.raceData = {
  "races": [
    {
      "raceId": 1,
      "trackName": "Bahrain",
      "weather": "Cloudy",
      "results": [
        {"position": 1, "name": "Nico Hulkenberg", "team": "Haas", "points": 25, "time": 5241.59, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 2, "name": "Alex Albon", "team": "Williams", "points": 18, "time": 5236.11, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 3, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 15, "time": 5235.69, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 4, "name": "Esteban Ocon", "team": "Alpine", "points": 12, "time": 5241.94, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 5, "name": "George Russell", "team": "Mercedes", "points": 10, "time": 5242.73, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 6, "name": "Pierre Gasly", "team": "Alpine", "points": 8, "time": 5270.18, "overtakes": 0, "tyreDegradation": 74, "pits": 1},
        {"position": 7, "name": "Kevin Magnussen", "team": "Haas", "points": 6, "time": 5259.93, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 8, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 4, "time": 5243.21, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 9, "name": "Lance Stroll", "team": "Aston Martin", "points": 2, "time": 5244.91, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 10, "name": "Lando Norris", "team": "McLaren", "points": 1, "time": 5263.66, "overtakes": 0, "tyreDegradation": 73, "pits": 1},
        {"position": 11, "name": "Max Verstappen", "team": "Red Bull", "points": 0, "time": 5259.63, "overtakes": 0, "tyreDegradation": 74, "pits": 1},
        {"position": 12, "name": "Charles Leclerc", "team": "Ferrari", "points": 0, "time": 5258.9, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 13, "name": "Daniel Ricciardo", "team": "RB", "points": 0, "time": 5240.17, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 14, "name": "Logan Sargeant", "team": "Williams", "points": 0, "time": 5238.24, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 15, "name": "Sergio Perez", "team": "Red Bull", "points": 0, "time": 5254.94, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 16, "name": "Yuki Tsunoda", "team": "RB", "points": 0, "time": 5241.96, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 17, "name": "Carlos Sainz", "team": "Ferrari", "points": 0, "time": 5260.96, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 18, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "time": 5254.55, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 19, "name": "Lewis Hamilton", "team": "Mercedes", "points": 0, "time": 5244.49, "overtakes": 0, "tyreDegradation": 77, "pits": 0},
        {"position": 20, "name": "Oscar Piastri", "team": "McLaren", "points": 0, "time": 5252.33, "overtakes": 1, "tyreDegradation": 77, "pits": 0}
      ]
    },
    {
      "raceId": 2,
      "trackName": "Saudi Arabia",
      "weather": "Clear",
      "results": [
        {"position": 1, "name": "Lando Norris", "team": "McLaren", "points": 25, "time": 5337.34, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 2, "name": "Lewis Hamilton", "team": "Mercedes", "points": 18, "time": 5341.22, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 3, "name": "Charles Leclerc", "team": "Ferrari", "points": 15, "time": 5353.25, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 4, "name": "Nico Hulkenberg", "team": "Haas", "points": 12, "time": 5345.22, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 5, "name": "Max Verstappen", "team": "Red Bull", "points": 10, "time": 5362.58, "overtakes": 1, "tyreDegradation": 78, "pits": 0},
        {"position": 6, "name": "Esteban Ocon", "team": "Alpine", "points": 8, "time": 5325.54, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 7, "name": "Yuki Tsunoda", "team": "RB", "points": 6, "time": 5351.17, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 8, "name": "Sergio Perez", "team": "Red Bull", "points": 4, "time": 5336.22, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 9, "name": "Kevin Magnussen", "team": "Haas", "points": 2, "time": 5368.33, "overtakes": 1, "tyreDegradation": 78, "pits": 0},
        {"position": 10, "name": "George Russell", "team": "Mercedes", "points": 1, "time": 5329.93, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 11, "name": "Oscar Piastri", "team": "McLaren", "points": 0, "time": 5328.43, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 12, "name": "Pierre Gasly", "team": "Alpine", "points": 0, "time": 5345.81, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 13, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 0, "time": 5328.96, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 14, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "time": 5356.25, "overtakes": 1, "tyreDegradation": 64, "pits": 1},
        {"position": 15, "name": "Alex Albon", "team": "Williams", "points": 0, "time": 5332.5, "overtakes": 1, "tyreDegradation": 78, "pits": 0},
        {"position": 16, "name": "Daniel Ricciardo", "team": "RB", "points": 0, "time": 5348.06, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 17, "name": "Logan Sargeant", "team": "Williams", "points": 0, "time": 5353.93, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 18, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 0, "time": 5345.45, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 19, "name": "Lance Stroll", "team": "Aston Martin", "points": 0, "time": 5346.04, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 20, "name": "Carlos Sainz", "team": "Ferrari", "points": 0, "time": 5358.76, "overtakes": 0, "tyreDegradation": 78, "pits": 0}
      ]
    },
    {
      "raceId": 3,
      "trackName": "Australia",
      "weather": "Rain",
      "results": [
        {"position": 1, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 25, "time": 5439.34, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 2, "name": "Yuki Tsunoda", "team": "RB", "points": 18, "time": 5425.92, "overtakes": 1, "tyreDegradation": 80, "pits": 0},
        {"position": 3, "name": "Carlos Sainz", "team": "Ferrari", "points": 15, "time": 5440.19, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 4, "name": "Oscar Piastri", "team": "McLaren", "points": 12, "time": 5443.83, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 5, "name": "Charles Leclerc", "team": "Ferrari", "points": 10, "time": 5424.37, "overtakes": 1, "tyreDegradation": 80, "pits": 0},
        {"position": 6, "name": "Pierre Gasly", "team": "Alpine", "points": 8, "time": 5422.77, "overtakes": 1, "tyreDegradation": 80, "pits": 0},
        {"position": 7, "name": "Sergio Perez", "team": "Red Bull", "points": 6, "time": 5435.73, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 8, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 4, "time": 5406.26, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 9, "name": "Esteban Ocon", "team": "Alpine", "points": 2, "time": 5449.57, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 10, "name": "Logan Sargeant", "team": "Williams", "points": 1, "time": 5432.71, "overtakes": 1, "tyreDegradation": 80, "pits": 0},
        {"position": 11, "name": "George Russell", "team": "Mercedes", "points": 0, "time": 5442.31, "overtakes": 0, "tyreDegradation": 80, "pits": 1},
        {"position": 12, "name": "Lando Norris", "team": "McLaren", "points": 0, "time": 5434.16, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 13, "name": "Max Verstappen", "team": "Red Bull", "points": 0, "time": 5453, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 14, "name": "Alex Albon", "team": "Williams", "points": 0, "time": 5436.07, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 15, "name": "Lewis Hamilton", "team": "Mercedes", "points": 0, "time": 5452.14, "overtakes": 1, "tyreDegradation": 80, "pits": 0},
        {"position": 16, "name": "Lance Stroll", "team": "Aston Martin", "points": 0, "time": 5435.02, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 17, "name": "Daniel Ricciardo", "team": "RB", "points": 0, "time": 5441.1, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 18, "name": "Nico Hulkenberg", "team": "Haas", "points": 0, "time": 5425.02, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 19, "name": "Kevin Magnussen", "team": "Haas", "points": 0, "time": 5463.51, "overtakes": 0, "tyreDegradation": 80, "pits": 1},
        {"position": 20, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "time": 5434.37, "overtakes": 1, "tyreDegradation": 80, "pits": 0}
      ]
    },
    {
      "raceId": 4,
      "trackName": "Japan",
      "weather": "Sunny",
      "results": [
        {"position": 1, "name": "Pierre Gasly", "team": "Alpine", "points": 25, "time": 5342.55, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 2, "name": "George Russell", "team": "Mercedes", "points": 18, "time": 5355, "overtakes": 1, "tyreDegradation": 78, "pits": 0},
        {"position": 3, "name": "Logan Sargeant", "team": "Williams", "points": 15, "time": 5331.4, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 4, "name": "Nico Hulkenberg", "team": "Haas", "points": 12, "time": 5348.58, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 5, "name": "Sergio Perez", "team": "Red Bull", "points": 10, "time": 5341.08, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 6, "name": "Kevin Magnussen", "team": "Haas", "points": 8, "time": 5343.48, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 7, "name": "Carlos Sainz", "team": "Ferrari", "points": 6, "time": 5347.14, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 8, "name": "Oscar Piastri", "team": "McLaren", "points": 4, "time": 5341.89, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 9, "name": "Lando Norris", "team": "McLaren", "points": 2, "time": 5349.75, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 10, "name": "Daniel Ricciardo", "team": "RB", "points": 1, "time": 5334.82, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 11, "name": "Alex Albon", "team": "Williams", "points": 0, "time": 5365.24, "overtakes": 0, "tyreDegradation": 77, "pits": 1},
        {"position": 12, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "time": 5331.69, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 13, "name": "Charles Leclerc", "team": "Ferrari", "points": 0, "time": 5356.75, "overtakes": 1, "tyreDegradation": 78, "pits": 0},
        {"position": 14, "name": "Esteban Ocon", "team": "Alpine", "points": 0, "time": 5331.93, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 15, "name": "Max Verstappen", "team": "Red Bull", "points": 0, "time": 5332.22, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 16, "name": "Yuki Tsunoda", "team": "RB", "points": 0, "time": 5354.93, "overtakes": 1, "tyreDegradation": 78, "pits": 1},
        {"position": 17, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 0, "time": 5325.11, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 18, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 0, "time": 5316.02, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 19, "name": "Lance Stroll", "team": "Aston Martin", "points": 0, "time": 5338.65, "overtakes": 0, "tyreDegradation": 78, "pits": 0},
        {"position": 20, "name": "Lewis Hamilton", "team": "Mercedes", "points": 0, "time": 5323.45, "overtakes": 0, "tyreDegradation": 78, "pits": 0}
      ]
    },
    {
      "raceId": 5,
      "trackName": "China",
      "weather": "Cloudy",
      "results": [
        {"position": 1, "name": "Logan Sargeant", "team": "Williams", "points": 25, "time": 5427.71, "overtakes": 1, "tyreDegradation": 80, "pits": 0},
        {"position": 2, "name": "Sergio Perez", "team": "Red Bull", "points": 18, "time": 5426.71, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 3, "name": "Alex Albon", "team": "Williams", "points": 15, "time": 5423.83, "overtakes": 1, "tyreDegradation": 80, "pits": 0},
        {"position": 4, "name": "Esteban Ocon", "team": "Alpine", "points": 12, "time": 5437.54, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 5, "name": "Nico Hulkenberg", "team": "Haas", "points": 10, "time": 5416.39, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 6, "name": "Max Verstappen", "team": "Red Bull", "points": 8, "time": 5437.64, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 7, "name": "George Russell", "team": "Mercedes", "points": 6, "time": 5437.95, "overtakes": 1, "tyreDegradation": 80, "pits": 0},
        {"position": 8, "name": "Charles Leclerc", "team": "Ferrari", "points": 4, "time": 5415.73, "overtakes": 1, "tyreDegradation": 80, "pits": 0},
        {"position": 9, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 2, "time": 5438, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 10, "name": "Lance Stroll", "team": "Aston Martin", "points": 1, "time": 5444.68, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 11, "name": "Oscar Piastri", "team": "McLaren", "points": 0, "time": 5433.76, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 12, "name": "Yuki Tsunoda", "team": "RB", "points": 0, "time": 5442.55, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 13, "name": "Lando Norris", "team": "McLaren", "points": 0, "time": 5427.12, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 14, "name": "Carlos Sainz", "team": "Ferrari", "points": 0, "time": 5446.82, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 15, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 0, "time": 5417.36, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 16, "name": "Daniel Ricciardo", "team": "RB", "points": 0, "time": 5436.02, "overtakes": 0, "tyreDegradation": 80, "pits": 1},
        {"position": 17, "name": "Kevin Magnussen", "team": "Haas", "points": 0, "time": 5412.18, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 18, "name": "Lewis Hamilton", "team": "Mercedes", "points": 0, "time": 5464.16, "overtakes": 0, "tyreDegradation": 80, "pits": 2},
        {"position": 19, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "time": 5421.7, "overtakes": 0, "tyreDegradation": 80, "pits": 0},
        {"position": 20, "name": "Pierre Gasly", "team": "Alpine", "points": 0, "time": 5405.74, "overtakes": 0, "tyreDegradation": 80, "pits": 0}
      ]
    }
  ],
  "standings": [
    {"rank": 1, "name": "Nico Hulkenberg", "team": "Haas", "points": 59, "totalTime": 26776.8},
    {"rank": 2, "name": "Pierre Gasly", "team": "Alpine", "points": 41, "totalTime": 26787.1},
    {"rank": 3, "name": "Logan Sargeant", "team": "Williams", "points": 41, "totalTime": 26784},
    {"rank": 4, "name": "Sergio Perez", "team": "Red Bull", "points": 38, "totalTime": 26794.7},
    {"rank": 5, "name": "George Russell", "team": "Mercedes", "points": 35, "totalTime": 26807.9},
    {"rank": 6, "name": "Esteban Ocon", "team": "Alpine", "points": 34, "totalTime": 26786.5},
    {"rank": 7, "name": "Alex Albon", "team": "Williams", "points": 33, "totalTime": 26793.8},
    {"rank": 8, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 31, "totalTime": 26791.1},
    {"rank": 9, "name": "Charles Leclerc", "team": "Ferrari", "points": 29, "totalTime": 26809},
    {"rank": 10, "name": "Lando Norris", "team": "McLaren", "points": 28, "totalTime": 26812},
    {"rank": 11, "name": "Yuki Tsunoda", "team": "RB", "points": 24, "totalTime": 26816.5},
    {"rank": 12, "name": "Carlos Sainz", "team": "Ferrari", "points": 21, "totalTime": 26853.9},
    {"rank": 13, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 19, "totalTime": 26704.3},
    {"rank": 14, "name": "Lewis Hamilton", "team": "Mercedes", "points": 18, "totalTime": 26825.5},
    {"rank": 15, "name": "Max Verstappen", "team": "Red Bull", "points": 18, "totalTime": 26845.1},
    {"rank": 16, "name": "Oscar Piastri", "team": "McLaren", "points": 16, "totalTime": 26800.2},
    {"rank": 17, "name": "Kevin Magnussen", "team": "Haas", "points": 16, "totalTime": 26847.4},
    {"rank": 18, "name": "Lance Stroll", "team": "Aston Martin", "points": 3, "totalTime": 26809.3},
    {"rank": 19, "name": "Daniel Ricciardo", "team": "RB", "points": 1, "totalTime": 26800.2},
    {"rank": 20, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "totalTime": 26798.6}
  ]
};
