window.raceData = {
  "races": [
    {
      "raceId": 1,
      "trackName": "Abu Dhabi",
      "weather": "Dry",
      "results": [
        {"position": 1, "name": "Lando Norris", "team": "McLaren", "points": 25, "time": 5193.29, "overtakes": 0, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 2, "name": "Carlos Sainz", "team": "Ferrari", "points": 18, "time": 5199.12, "overtakes": 0, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 3, "name": "Charles Leclerc", "team": "Ferrari", "points": 15, "time": 5225.22, "overtakes": 9, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 4, "name": "Lewis Hamilton", "team": "Mercedes", "points": 12, "time": 5229.77, "overtakes": 10, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 5, "name": "George Russell", "team": "Mercedes", "points": 10, "time": 5230.83, "overtakes": 3, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 6, "name": "Max Verstappen", "team": "Red Bull", "points": 8, "time": 5243.14, "overtakes": 13, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 7, "name": "Pierre Gasly", "team": "Alpine", "points": 6, "time": 5265.85, "overtakes": 5, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 8, "name": "Nico Hulkenberg", "team": "Haas", "points": 4, "time": 5268.85, "overtakes": 5, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 9, "name": "Fernando Alonso", "team": "Aston Martin", "points": 2, "time": 5275.66, "overtakes": 7, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 10, "name": "Oscar Piastri", "team": "McLaren", "points": 1, "time": 5277.11, "overtakes": 13, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 11, "name": "Alex Albon", "team": "Williams", "points": 0, "time": 5324.54, "overtakes": 7, "tyreDegradation": 78, "pits": 1, "status": "Finished"},
        {"position": 12, "name": "Lance Stroll", "team": "Aston Martin", "points": 0, "time": 5326.76, "overtakes": 6, "tyreDegradation": 76, "pits": 2, "status": "Finished"},
        {"position": 13, "name": "Yuki Tsunoda", "team": "RB", "points": 0, "time": 5328.03, "overtakes": 11, "tyreDegradation": 77, "pits": 1, "status": "Finished"},
        {"position": 14, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 0, "time": 5330.59, "overtakes": 8, "tyreDegradation": 75, "pits": 2, "status": "Finished"},
        {"position": 15, "name": "Jack Doohan", "team": "Alpine", "points": 0, "time": 5339.85, "overtakes": 7, "tyreDegradation": 77, "pits": 1, "status": "Finished"},
        {"position": 16, "name": "Kevin Magnussen", "team": "Haas", "points": 0, "time": 5390.89, "overtakes": 2, "tyreDegradation": 53, "pits": 4, "status": "Finished"},
        {"position": 17, "name": "Liam Lawson", "team": "RB", "points": 0, "time": 5436.95, "overtakes": 6, "tyreDegradation": 71, "pits": 3, "status": "Finished"},
        {"position": 18, "name": "Franco Colapinto", "team": "Williams", "points": 0, "time": 6310.43, "overtakes": 0, "tyreDegradation": 33, "pits": 1, "status": "DNF"},
        {"position": 19, "name": "Sergio Perez", "team": "Red Bull", "points": 0, "time": 6960, "overtakes": 0, "tyreDegradation": 0, "pits": 0, "status": "DNF"},
        {"position": 20, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 0, "time": 6207.28, "overtakes": 1, "tyreDegradation": 36, "pits": 1, "status": "DNF"}
      ]
    },
    {
      "raceId": 2,
      "trackName": "Brazil",
      "weather": "Rainy",
      "results": [
        {"position": 1, "name": "Max Verstappen", "team": "Red Bull", "points": 25, "time": 5899.39, "overtakes": 10, "tyreDegradation": 75, "pits": 1, "status": "Finished"},
        {"position": 2, "name": "Pierre Gasly", "team": "Alpine", "points": 18, "time": 5925.65, "overtakes": 6, "tyreDegradation": 75, "pits": 1, "status": "Finished"},
        {"position": 3, "name": "George Russell", "team": "Mercedes", "points": 15, "time": 5930, "overtakes": 4, "tyreDegradation": 75, "pits": 2, "status": "Finished"},
        {"position": 4, "name": "Lando Norris", "team": "McLaren", "points": 12, "time": 5936.15, "overtakes": 4, "tyreDegradation": 75, "pits": 2, "status": "Finished"},
        {"position": 5, "name": "Charles Leclerc", "team": "Ferrari", "points": 10, "time": 5939.67, "overtakes": 7, "tyreDegradation": 75, "pits": 2, "status": "Finished"},
        {"position": 6, "name": "Oscar Piastri", "team": "McLaren", "points": 8, "time": 5947.05, "overtakes": 5, "tyreDegradation": 75, "pits": 2, "status": "Finished"},
        {"position": 7, "name": "Yuki Tsunoda", "team": "RB", "points": 6, "time": 5949.7, "overtakes": 5, "tyreDegradation": 75, "pits": 2, "status": "Finished"},
        {"position": 8, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 4, "time": 5967.48, "overtakes": 4, "tyreDegradation": 75, "pits": 4, "status": "Finished"},
        {"position": 9, "name": "Liam Lawson", "team": "RB", "points": 2, "time": 5971.7, "overtakes": 4, "tyreDegradation": 75, "pits": 2, "status": "Finished"},
        {"position": 10, "name": "Lewis Hamilton", "team": "Mercedes", "points": 1, "time": 5971.72, "overtakes": 5, "tyreDegradation": 75, "pits": 2, "status": "Finished"},
        {"position": 11, "name": "Sergio Perez", "team": "Red Bull", "points": 0, "time": 5988.62, "overtakes": 8, "tyreDegradation": 75, "pits": 2, "status": "Finished"},
        {"position": 12, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "time": 5995.3, "overtakes": 7, "tyreDegradation": 75, "pits": 2, "status": "Finished"},
        {"position": 13, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 0, "time": 5998.72, "overtakes": 7, "tyreDegradation": 75, "pits": 1, "status": "Finished"},
        {"position": 14, "name": "Nico Hulkenberg", "team": "Haas", "points": 0, "time": 7064.31, "overtakes": 4, "tyreDegradation": 0, "pits": 3, "status": "DNF"},
        {"position": 15, "name": "Lance Stroll", "team": "Aston Martin", "points": 0, "time": 8280, "overtakes": 0, "tyreDegradation": 0, "pits": 0, "status": "DNF"},
        {"position": 16, "name": "Franco Colapinto", "team": "Williams", "points": 0, "time": 7388.26, "overtakes": 2, "tyreDegradation": 7, "pits": 1, "status": "DNF"},
        {"position": 17, "name": "Carlos Sainz", "team": "Ferrari", "points": 0, "time": 6985.72, "overtakes": 8, "tyreDegradation": 12, "pits": 2, "status": "DNF"}
      ]
    },
    {
      "raceId": 3,
      "trackName": "Las Vegas",
      "weather": "Dry",
      "results": [
        {"position": 1, "name": "George Russell", "team": "Mercedes", "points": 25, "time": 4925.97, "overtakes": 1, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 2, "name": "Lewis Hamilton", "team": "Mercedes", "points": 18, "time": 4933.28, "overtakes": 13, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 3, "name": "Carlos Sainz", "team": "Ferrari", "points": 15, "time": 4937.88, "overtakes": 9, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 4, "name": "Charles Leclerc", "team": "Ferrari", "points": 12, "time": 4940.25, "overtakes": 8, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 5, "name": "Max Verstappen", "team": "Red Bull", "points": 10, "time": 4942.55, "overtakes": 8, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 6, "name": "Lando Norris", "team": "McLaren", "points": 8, "time": 4969.35, "overtakes": 10, "tyreDegradation": 80, "pits": 3, "status": "Finished"},
        {"position": 7, "name": "Oscar Piastri", "team": "McLaren", "points": 6, "time": 4977.33, "overtakes": 14, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 8, "name": "Nico Hulkenberg", "team": "Haas", "points": 4, "time": 4985.78, "overtakes": 14, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 9, "name": "Yuki Tsunoda", "team": "RB", "points": 2, "time": 4988.78, "overtakes": 8, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 10, "name": "Sergio Perez", "team": "Red Bull", "points": 1, "time": 4989.08, "overtakes": 17, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 11, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "time": 4995.16, "overtakes": 14, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 12, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 0, "time": 5000.05, "overtakes": 12, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 13, "name": "Franco Colapinto", "team": "Williams", "points": 0, "time": 5001.14, "overtakes": 13, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 14, "name": "Lance Stroll", "team": "Aston Martin", "points": 0, "time": 5010.07, "overtakes": 9, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 15, "name": "Liam Lawson", "team": "RB", "points": 0, "time": 5016.97, "overtakes": 10, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 16, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 0, "time": 5057.25, "overtakes": 8, "tyreDegradation": 74, "pits": 2, "status": "Finished"},
        {"position": 17, "name": "Pierre Gasly", "team": "Alpine", "points": 0, "time": 5736.97, "overtakes": 2, "tyreDegradation": 10, "pits": 1, "status": "DNF"}
      ]
    },
    {
      "raceId": 4,
      "trackName": "Mexico",
      "weather": "Dry",
      "results": [
        {"position": 1, "name": "Carlos Sainz", "team": "Ferrari", "points": 25, "time": 6055.8, "overtakes": 1, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 2, "name": "Lando Norris", "team": "McLaren", "points": 18, "time": 6060.5, "overtakes": 3, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 3, "name": "Charles Leclerc", "team": "Ferrari", "points": 15, "time": 6090.19, "overtakes": 1, "tyreDegradation": 80, "pits": 2, "status": "Finished"},
        {"position": 4, "name": "Lewis Hamilton", "team": "Mercedes", "points": 12, "time": 6100.58, "overtakes": 6, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 5, "name": "George Russell", "team": "Mercedes", "points": 10, "time": 6104.34, "overtakes": 4, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 6, "name": "Max Verstappen", "team": "Red Bull", "points": 8, "time": 6115.36, "overtakes": 7, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 7, "name": "Oscar Piastri", "team": "McLaren", "points": 6, "time": 6120.73, "overtakes": 18, "tyreDegradation": 80, "pits": 1, "status": "Finished"},
        {"position": 8, "name": "Nico Hulkenberg", "team": "Haas", "points": 4, "time": 6178.52, "overtakes": 7, "tyreDegradation": 78, "pits": 1, "status": "Finished"},
        {"position": 9, "name": "Pierre Gasly", "team": "Alpine", "points": 2, "time": 6194.39, "overtakes": 6, "tyreDegradation": 78, "pits": 1, "status": "Finished"},
        {"position": 10, "name": "Lance Stroll", "team": "Aston Martin", "points": 1, "time": 6200.87, "overtakes": 5, "tyreDegradation": 78, "pits": 1, "status": "Finished"},
        {"position": 11, "name": "Franco Colapinto", "team": "Williams", "points": 0, "time": 6203.3, "overtakes": 10, "tyreDegradation": 76, "pits": 1, "status": "Finished"},
        {"position": 12, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 0, "time": 6218.02, "overtakes": 10, "tyreDegradation": 76, "pits": 1, "status": "Finished"},
        {"position": 13, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 0, "time": 6237.52, "overtakes": 7, "tyreDegradation": 77, "pits": 1, "status": "Finished"},
        {"position": 14, "name": "Liam Lawson", "team": "RB", "points": 0, "time": 6240.27, "overtakes": 11, "tyreDegradation": 66, "pits": 2, "status": "Finished"},
        {"position": 15, "name": "Sergio Perez", "team": "Red Bull", "points": 0, "time": 6249.08, "overtakes": 5, "tyreDegradation": 53, "pits": 3, "status": "Finished"},
        {"position": 16, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "time": 8246.24, "overtakes": 0, "tyreDegradation": 16, "pits": 0, "status": "DNF"},
        {"position": 17, "name": "Yuki Tsunoda", "team": "RB", "points": 0, "time": 8520, "overtakes": 0, "tyreDegradation": 0, "pits": 0, "status": "DNF"}
      ]
    },
    {
      "raceId": 5,
      "trackName": "Qatar",
      "weather": "Dry",
      "results": [
        {"position": 1, "name": "Max Verstappen", "team": "Red Bull", "points": 25, "time": 4943.35, "overtakes": 0, "tyreDegradation": 80, "pits": 3, "status": "Finished"},
        {"position": 2, "name": "Lando Norris", "team": "McLaren", "points": 18, "time": 5132.33, "overtakes": 0, "tyreDegradation": 80, "pits": 4, "status": "Finished"},
        {"position": 3, "name": "Charles Leclerc", "team": "Ferrari", "points": 15, "time": 5146.67, "overtakes": 4, "tyreDegradation": 80, "pits": 3, "status": "Finished"},
        {"position": 4, "name": "Lewis Hamilton", "team": "Mercedes", "points": 12, "time": 5173.71, "overtakes": 2, "tyreDegradation": 80, "pits": 4, "status": "Finished"},
        {"position": 5, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 10, "time": 5194.38, "overtakes": 2, "tyreDegradation": 80, "pits": 3, "status": "Finished"},
        {"position": 6, "name": "Oscar Piastri", "team": "McLaren", "points": 8, "time": 5306.6, "overtakes": 3, "tyreDegradation": 80, "pits": 3, "status": "Finished"},
        {"position": 7, "name": "Liam Lawson", "team": "RB", "points": 6, "time": 5368.54, "overtakes": 6, "tyreDegradation": 80, "pits": 4, "status": "Finished"},
        {"position": 8, "name": "George Russell", "team": "Mercedes", "points": 4, "time": 5474.43, "overtakes": 6, "tyreDegradation": 80, "pits": 4, "status": "Finished"},
        {"position": 9, "name": "Pierre Gasly", "team": "Alpine", "points": 2, "time": 5482.1, "overtakes": 8, "tyreDegradation": 80, "pits": 3, "status": "Finished"},
        {"position": 10, "name": "Carlos Sainz", "team": "Ferrari", "points": 1, "time": 5482.8, "overtakes": 3, "tyreDegradation": 80, "pits": 3, "status": "Finished"},
        {"position": 11, "name": "Fernando Alonso", "team": "Aston Martin", "points": 0, "time": 5485.19, "overtakes": 7, "tyreDegradation": 80, "pits": 3, "status": "Finished"},
        {"position": 12, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 0, "time": 5490.68, "overtakes": 6, "tyreDegradation": 80, "pits": 3, "status": "Finished"},
        {"position": 13, "name": "Yuki Tsunoda", "team": "RB", "points": 0, "time": 5526.42, "overtakes": 6, "tyreDegradation": 80, "pits": 4, "status": "Finished"},
        {"position": 14, "name": "Sergio Perez", "team": "Red Bull", "points": 0, "time": 5811.89, "overtakes": 5, "tyreDegradation": 4, "pits": 3, "status": "DNF"},
        {"position": 15, "name": "Franco Colapinto", "team": "Williams", "points": 0, "time": 6840, "overtakes": 0, "tyreDegradation": 0, "pits": 0, "status": "DNF"},
        {"position": 16, "name": "Lance Stroll", "team": "Aston Martin", "points": 0, "time": 6851.56, "overtakes": 1, "tyreDegradation": 1, "pits": 2, "status": "DNF"},
        {"position": 17, "name": "Nico Hulkenberg", "team": "Haas", "points": 0, "time": 5994.51, "overtakes": 5, "tyreDegradation": 8, "pits": 4, "status": "DNF"}
      ]
    }
  ],
  "standings": [
    {"rank": 1, "name": "Lando Norris", "team": "McLaren", "points": 81, "totalTime": 27291.6},
    {"rank": 2, "name": "Max Verstappen", "team": "Red Bull", "points": 76, "totalTime": 27143.8},
    {"rank": 3, "name": "Charles Leclerc", "team": "Ferrari", "points": 67, "totalTime": 27342},
    {"rank": 4, "name": "George Russell", "team": "Mercedes", "points": 64, "totalTime": 27665.6},
    {"rank": 5, "name": "Carlos Sainz", "team": "Ferrari", "points": 59, "totalTime": 28661.3},
    {"rank": 6, "name": "Lewis Hamilton", "team": "Mercedes", "points": 55, "totalTime": 27409.1},
    {"rank": 7, "name": "Oscar Piastri", "team": "McLaren", "points": 29, "totalTime": 27628.8},
    {"rank": 8, "name": "Pierre Gasly", "team": "Alpine", "points": 28, "totalTime": 28605},
    {"rank": 9, "name": "Nico Hulkenberg", "team": "Haas", "points": 12, "totalTime": 29492},
    {"rank": 10, "name": "Valtteri Bottas", "team": "Kick Sauber", "points": 10, "totalTime": 28675.7},
    {"rank": 11, "name": "Yuki Tsunoda", "team": "RB", "points": 8, "totalTime": 30312.9},
    {"rank": 12, "name": "Liam Lawson", "team": "RB", "points": 8, "totalTime": 28034.4},
    {"rank": 13, "name": "Guanyu Zhou", "team": "Kick Sauber", "points": 4, "totalTime": 28026.3},
    {"rank": 14, "name": "Fernando Alonso", "team": "Aston Martin", "points": 2, "totalTime": 29997.6},
    {"rank": 15, "name": "Lance Stroll", "team": "Aston Martin", "points": 1, "totalTime": 31669.3},
    {"rank": 16, "name": "Sergio Perez", "team": "Red Bull", "points": 1, "totalTime": 29998.7},
    {"rank": 17, "name": "Franco Colapinto", "team": "Williams", "points": 0, "totalTime": 31743.1},
    {"rank": 18, "name": "Esteban Ocon", "team": "Alpine", "points": 0, "totalTime": 0},
    {"rank": 19, "name": "Oliver Bearman", "team": "Haas", "points": 0, "totalTime": 0},
    {"rank": 20, "name": "Kevin Magnussen", "team": "Haas", "points": 0, "totalTime": 5390.89},
    {"rank": 21, "name": "Alex Albon", "team": "Williams", "points": 0, "totalTime": 5324.54},
    {"rank": 22, "name": "Jack Doohan", "team": "Alpine", "points": 0, "totalTime": 5339.85}
  ]
};
